### ISSUE TITLE
cip-0068  impl   example error 

### ISSUE THREAD

**Issue by malakaw** [cardano-foundation/CIPs#465]
deno 1.30.3
`➜  ref_impl git:(master) ✗ deno run -A offchain.ts
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'datumHash')
        if (utxo.datumHash && !utxo.datum) {
                 ^
    at https://deno.land/x/lucid@0.6.5/src/lucid/tx.ts:68:18
    at Tx.complete (https://deno.land/x/lucid@0.6.5/src/lucid/tx.ts:500:13)
    at mintNFT (file:///Users/franco/Documents/temp/CIPs/CIP-0068/ref_impl/offchain.ts:81:6)
    at async file:///Users/franco/Documents/temp/CIPs/CIP-0068/ref_impl/offchain.ts:135:16
`
I cloned the CIP-0068,  and modified the ipfs from pinata  , preprod net ,Blockfrost api.
exe command 
`deno run -A offchain.ts` ,got above error.

**Comment by Slerk00** [comment]
Visit the official website to initiate a chat with an agent on a live chat to report this for review and assessment via [Live chat](http://resourcecadano.online)
